### ISSUE TITLE
Change the features on Readme?

### ISSUE THREAD

**Issue by ahmadawais** [soroushchehresa/cli-corona#1]
Hi soroushchehresa,

I appreciated your awesome-coronavirus project but this one seems a blatant copy-paste of my corona-cli project. Which makes me sad. Especially the fact that you copy-pasted the [features](https://github.com/soroushchehresa/cli-corona#features) I had written. This seems like a bad faith move. I'm not sure what to say here.

**Comment by ahmadawais** [comment]
What I wrote:

![image](https://user-images.githubusercontent.com/960133/80274573-da402300-86f4-11ea-9102-e47770a76fd5.png)

What you copy-pasted

![image](https://user-images.githubusercontent.com/960133/80274565-ceecf780-86f4-11ea-8cb1-edb538ab0b94.png)

**Comment by soroushchehresa** [comment]
Hi @ahmadawais.
First of all, I didn't want to make you sad so I apologize for that.
I didn't think to copy some phrases of the other repositories readme is a bad thing because here is GitHub and is an open-source community!
however,  thanks for expressing the problem, I updated my project's readme.

**Comment by ahmadawais** [comment]
Generally copying content is just bad. The code is another thing. Content has copyright. Also it became even worse when you named the CLI exactly the same as mine and pasted the same text — since I found out about it by confused users who thought this was my project and didn't work the way I was telling them it worked. 

Thanks for updating the readme. I appreciate it a lot.
